[database]
path = "../数据库.db"
mongo_uri = "mongodb://localhost:27017"
db_name = "weiboData"

[cookies]
SCF = "AiEw0Due2-IQnV5CuIpy9BTYQJzTTPBL9MT7F738zokBuDAvn5GnVgxDiyUgrQzju8CcVUgUNwKQk2N_0Wzfo9k."
SUB = "_2A25FO3_mDeRhGeVL7lcZ8SnMyD2IHXVmOf0urDV8PUNbmtAbLVnikW9NTC2xlBdW0e_r9KISuUfFAip0hPdYVnuC"
SUBP = "0033WrSXqPxfM725Ws9jqgMF55529P9D9WhY6g1xxUE-zR.iFG6nWcuO5JpX5KzhUgL.FoefSK-ReKM7e022dJLoI7_KdfvBdcvEPfxE9Btt"
ALF = "02_1751555254"
SINAGLOBAL = ""
_s_tentry = ""
Apache = ""
ULV = ""
XSRF-TOKEN = ""
PC_TOKEN = ""
WBPSESS = ""
ALC = "ALC-3SDQrB-1748963254-4-1239660047-52adda4ec597334b52df290cb273-2"
X-CSRF-TOKEN = "CK-Yco09N_goCa0wJX9igRO-pV3scalZDXfRDVCzCaCMg_3axHF="

[cookies_info]
update_time = "2025-06-03 23:07:34"
