[database]
path = "../数据库.db"
mongo_uri = "mongodb://localhost:27017"
db_name = "weiboData"

[cookies]
SCF = "AkU7cSo2dlqCbUFV2YJOplEOVGiR3qQjJXJlmI8JtQgWUYLXJq6y3BgfjGN28z2tV6vPbZUfobWSMdZq7QMr4RU."
SUB = "_2A25K-PxODeRhGeVL7lcZ8SnMyD2IHXVmdHGGrDV8PUNbmtAbLVHikW9NTC2xlE8QZB0RCzSh-FDFwIgUH-HpfH1o"
SUBP = "0033WrSXqPxfM725Ws9jqgMF55529P9D9WhY6g1xxUE-zR.iFG6nWcuO5JpX5KzhUgL.FoefSK-ReKM7e022dJLoI7_KdfvBdcvEPfxE9Btt"
ALF = "02_1747196191"
SINAGLOBAL = ""
_s_tentry = ""
Apache = ""
ULV = ""
XSRF-TOKEN = ""
PC_TOKEN = ""
WBPSESS = ""
ALC = "ALC-3SDQrB-1744604191-4-1177933376-55bc4f90caf0d2a8c0a86bc2b784-2"
X-CSRF-TOKEN = "CK-Yco0-cau-C7I9JXv2NX-ZDWBBN8xZpWcBCXGzC_EYcR0wCoe="

[cookies_info]
update_time = "2025-04-14 12:16:31"
