[database]
path = "../数据库.db"
mongo_uri = "mongodb://localhost:27017"
db_name = "weiboData"

[cookies]
SCF = "AmBk8uKQSbZ9OUDDC0aKS1trZ4hY5tQSD8Hz2z3AiDhCaXub47-LA6V5n5lFULMOv0WM57jCuEFkDOVdb7EyHJs."
SUB = "_2A25K-M0FDeRhGeVL7lcZ8SnMyD2IHXVmdEDNrDV8PUNbmtAbLVjTkW9NTC2xlJBZV7Vg9H_7P2KhF1hjwefc1_dA"
SUBP = "0033WrSXqPxfM725Ws9jqgMF55529P9D9WhY6g1xxUE-zR.iFG6nWcuO5JpX5KzhUgL.FoefSK-ReKM7e022dJLoI7_KdfvBdcvEPfxE9Btt"
ALF = "02_1747208789"
SINAGLOBAL = ""
_s_tentry = ""
Apache = ""
ULV = ""
XSRF-TOKEN = ""
PC_TOKEN = ""
WBPSESS = ""
ALC = "ALC-3SDQrB-1744616789-4-815640633-8f96f7b704627a87bb3b4cb5672d-2"
X-CSRF-TOKEN = "CK-Yco0-ca1RcoEYJ_c2CWczx_SGD8x2p_I-gaFzNWFoN7EZc70="

[cookies_info]
update_time = "2025-04-14 15:46:29"
