[database]
path = "../数据库.db"
mongo_uri = "mongodb://localhost:27017"
db_name = "weiboData"

[cookies]
SCF = "AoTkA5s8-mp6q2-Mao37SlAd-ucQ7TNjPHchtq8gP36k9CFC74GJKiz094TO77C_egnTIpBO-2vnblWtsmj5tl8."
SUB = "_2A25FExTRDeRhGeFJ6VoU8yjMyj6IHXVmUSgZrDV8PUNbmtANLXHxkW9NfFnJFYWLbcC7QDce2RT-qLSFsHEEVMsi"
SUBP = "0033WrSXqPxfM725Ws9jqgMF55529P9D9WWNNx7-O0xJ4rQchFNa4B1I5JpX5KzhUgL.FoMNeonfe0q7eKz2dJLoIp7LxKML1KBLBKnLxKqL1hnLBoMNS0zRSKeceh2E"
ALF = "02_1748955521"
SINAGLOBAL = ""
_s_tentry = ""
Apache = ""
ULV = ""
XSRF-TOKEN = ""
PC_TOKEN = ""
WBPSESS = ""
ALC = "ALC-8r29gE-1746363521-1-889306524-4cb7521a490ed3589a051d3e950e-2"
X-CSRF-TOKEN = "CK-Yco0RCogoc_1wJ_uYxoe9xRcKNWlZpHwtN8gzCWCYC7gZx7F="

[cookies_info]
update_time = "2025-05-04 20:58:40"
